### ISSUE TITLE
Allure componets RBAC failures

### ISSUE THREAD

**Issue by juris** [qameta/helm-charts#17]
Trying to launch allure-ee helm chart and here's what in the logs

allure-ee-gateway pod 
```
2021-09-02 13:56:44.314  WARN 1 --- [oundedElastic-3] o.s.c.k.fabric8.Fabric8PodUtils          : Failed to get pod with name:[allure-ee-gateway-758b5f8cdc-bnr4w]. You should look into this if things aren't working as you expect. Are you missing serviceaccount permissions?

io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Pod]  with name: [allure-ee-gateway-758b5f8cdc-bnr4w]  in namespace: [allure]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64) ~[kubernetes-client-4.13.3.jar:na]
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72) ~[kubernetes-client-4.13.3.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:225) ~[kubernetes-client-4.13.3.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:186) ~[kubernetes-client-4.13.3.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:84) ~[kubernetes-client-4.13.3.jar:na]
```

allure-ee-report pod
```
2021-09-02 14:58:52.578 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing column [type] in table [`filter`]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.8.jar:5.3.8]
```

Here is the config.yml
```
version: 3.177.2

imagePullSecret: docker-hub
licenseKey: REDACTED

ingress:
  host: allure.local
  annotations:
    kubernetes.io/ingress.class: nginx-ext

gateway:
  service:
    type: ClusterIP

uaa:
  service:
    type: ClusterIP

report:
  service:
    type: ClusterIP
```

Kubernetes version: AWS EKS 1.20.8

**Comment by cheshi-mantu** [comment]
hi @juris 
these are to be submitted via https://support.qameta.io
